#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "photoview"
name = "Photoview"
description.en = "Simple and user-friendly photo gallery that's made for photographers "
description.fr = "Galerie photos simple et facile à utiliser, faite pour les photographes"

version = "2.3.13~ynh1"

maintainers = ["Jules Bertholet"]

[upstream]
license = "AGPL-3.0-only"
website = "https://photoview.github.io/"
demo = "https://photos.qpqp.dk/"
admindoc = "https://photoview.github.io/docs/"
code = "https://github.com/photoview/photoview"
fund = "https://github.com/sponsors/viktorstrate"

[integration]
yunohost = ">= 11.2.12"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "1000M"
ram.build = "2000M"
ram.runtime = "200M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.mapbox_token]
    ask.en = "Mapbox API token"
    ask.fr = "Clé API Mapbox"
    help.en = "Required for mapping features. You can get one for free at https://www.mapbox.com/"
    help.fr = "Nécessaire pour les fonctionnalités cartographiques. Vous pouvez en obtenir une gratuitement à https://www.mapbox.com/"
    type = "string"
    default = ""
    optional = true

[resources]
    [resources.sources]
    [resources.sources.main]
    url = "https://github.com/photoview/photoview/archive/refs/tags/v2.3.13.tar.gz"
    sha256 = "d512448fbefb6c209f1900c1d4e819f22b53de3f441df84a7a96f08a10dfb064"

    autoupdate.strategy = "latest_github_release"

    [resources.sources.libheif]
    url = "https://github.com/strukturag/libheif/releases/download/v1.12.0/libheif-1.12.0.tar.gz"
    sha256 = "e1ac2abb354fdc8ccdca71363ebad7503ad731c84022cf460837f0839e171718"

    autoupdate.strategy = "latest_github_release"
    autoupdate.upstream = "https://github.com/strukturag/libheif"
    autoupdate.asset = ".*\\.tar\\.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["media_cache"]

    [resources.permissions]
    main.url = "/"

    api.url = "/api"
    api.allowed = "visitors"
    api.auth_header = false
    api.protected = true

    share.url = "/share"
    share.allowed = "visitors"
    share.auth_header = false
    share.protected = true

    [resources.ports]
    main.default = 4001

    [resources.apt]
    packages = [
        "curl",
        "gpg",
        "ffmpeg",
        "exiftool",

        "libatlas-base-dev",
        "libblas-dev",
        "libdlib-dev",
        "libdlib19",
        "libjpeg-dev",
        "libjpeg-turbo8-dev",
        "liblapack-dev",

        # "darktable",
        "mariadb-server",
    ]

    packages_from_raw_bash = """
    if [[ $YNH_DEBIAN_VERSION == "bullseye" ]]; then
        echo "libdlib19";
    elif [[ $YNH_DEBIAN_VERSION == "bookworm" ]]; then
        echo "libdlib19.1";
    fi
    """

    [resources.apt.extras.strukturag_libheif]
    repo = "deb https://ppa.launchpadcontent.net/strukturag/libheif/ubuntu jammy main"
    key = "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xc6610628a707a7e5e391d27a9641080a705c2b92"
    packages = [
        "libheif-dev",
        "libaom-dev",
        "libx265-dev",
    ]

    [resources.apt.extras.strukturag_libde265]
    repo = "deb https://ppa.launchpadcontent.net/strukturag/libde265/ubuntu jammy main"
    key = "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xc6610628a707a7e5e391d27a9641080a705c2b92"
    packages = [
        "libde256-dev",
    ]

    [resources.apt.extras.yarn]
    repo = "deb https://dl.yarnpkg.com/debian/ stable main"
    key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
    packages = "yarn"

    [resources.database]
    type = "mysql"
